### PR TITLE
Team page updated

### PR DESCRIPTION
**Pull request by vedantgoswami**

### CODE REVIEW

**Review by deepdarshan21 — APPROVED** [review]
Thanks @vedantgoswami 
you have done amazing work

**Comment by deepdarshan21** [comment]
@vedantgoswami there is some problem in linking of the images.  Images are not loading in website

**Review by deepdarshan21 — COMMENTED** [review]
@vedantgoswami problem is that image that not correctly mentioned. you should mention like "../image/deepdarshan" instead of "image\deepdarshan.jpg" because 
1) in path address there is slash(/) not backslash(\)
2) image folder is outside of pages folder that why first you have first do back via(../) and then move to image folder via(image/) than to file(deepdarshan.jpg)
So resolve the bugs and then make a pull request again.

**Comment by vedantgoswami** [comment]
While I was testing on my pc it was working fine,please check the path of
the image .

**Comment by vedantgoswami** [comment]
Ok checking.....it

**Comment by deepdarshan21** [comment]
You can check the website it is not working there

**Pull request merged**
