### PR TITLE
Bug fixed

### PR DESCRIPTION
**Pull request by vedantgoswami**
please update website so that i can see the team page

### CODE REVIEW

**Comment by rajraman786** [comment]
@vedantgoswami attach the screenshots of bugs before and after fixed.

**Review by deepdarshan21 — APPROVED** [review]

**Comment by deepdarshan21** [comment]
@vedantgoswami now it is working good. Nice work

**Comment by deepdarshan21** [comment]
@vedantgoswami it remains one error with Kunal's photo....i fixed that

**Comment by vedantgoswami** [comment]
I need the photo of Kunal and prashant .

**Pull request merged**
